SCREEN_WIDTH: int = 700
SCREEN_HEIGHT: int = 700
BLOCK_SIZE: int = 50
SNAKE_COLOUR: str = "green"
APPLE_COLOUR: str = "red"
SCORE_TEXT_COLOUR: int = 0xFFFF14
DEATH_TEXT_COLOUR: str = "red"
HIGHSCORE_PATH: str = "data.bin"